theme: jekyll-theme-midnight

title: [Online Course - Machine learning for image processing]
description: [Using a scalable open-source framework for machine learning based image collection, annotation and classification]
