name: "MLimageCourse"
title: "ML image processing course"
description: |
  ML image processing course
base_url: https://fishsizeproject.github.io/Course-MLforImageProcessing/
repository_url: https://github.com/fishsizeproject/Course-MLforImageProcessing/
output_dir: "docs"
favicon: images/favicon.png
creative_commons: CC BY
twitter:
  site: "@mizer_model"
exclude: "README.md"
theme: mizer.css
navbar:
  source-url: true
  search: true
  right:
    - text: "Fish Size Project"
      href: https://fishsizeproject.org/
    - icon: "fab fa-github fa-lg"
      href: https://github.com/fishsizeproject/Course-MLforImageProcessing/
output:
  distill::distill_article:
    includes:
      in_header: giscus.html
    toc_depth: 2
